services:
    openresty-ixez:
        container_name: ${CONTAINER_NAME}
        image: openresty/openresty:1.21.4.1-3-alpine
        labels:
            createdBy: Apps
        network_mode: host
        restart: always
        volumes:
            - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
            - ./conf/fastcgi_params:/usr/local/openresty/nginx/conf/fastcgi_params
            - ./conf/fastcgi-php.conf:/usr/local/openresty/nginx/conf/fastcgi-php.conf
            - ./log:/var/log/nginx
            - ./conf/conf.d:/usr/local/openresty/nginx/conf/conf.d/
            - ./www:/www
            - ./root:/usr/share/nginx/html
            - /etc/localtime:/etc/localtime
version: "3"
